//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Apartment.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_APARTMENT_H)
#define _APARTMENT_H

#include "Room.h"

class Apartment
{
public:
	Apartment(int id, int number, double area, Room *room);
	int getNumber();
	double getArea();
	Room *getRoom();
	void displayApartment();

private:
	int apartmentId;
	int number;
	double area;
	Room *room;
};

#endif //_APARTMENT_H
