//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Apartment.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Apartment.h"
#include <iostream>

Apartment::Apartment(int id, int number, double area, Room *room)
{
    this->apartmentId = id;
    this->number = number;
    this->area = area;
    this->room = room;
}

int Apartment::getNumber()
{
    return number;
}

double Apartment::getArea()
{
    return area;
}

Room *Apartment::getRoom()
{
    return room;
}

void Apartment::displayApartment()
{
    std::cout << "Apartment ID: " << apartmentId << std::endl;
    std::cout << "Number: " << number << std::endl;
    std::cout << "Area: " << area << " m2" << std::endl;
    if (room != nullptr)
    {
        std::cout << "Room details:" << std::endl;
        room->displayRoom();
    }
}
