//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Building.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Building.h"
#include <iostream>

Building::Building(int id, string address)
{
    this->buildingId = id;
    this->address = address;
}

void Building::addApartment(Apartment *apartment)
{
    if (apartment != nullptr)
    {
        apartments.push_back(apartment);
    }
}

void Building::removeApartment(int apartmentId)
{
    for (auto it = apartments.begin(); it != apartments.end(); ++it)
    {
        if ((*it)->getNumber() == apartmentId)
        {
            apartments.erase(it);
            break;
        }
    }
}

void Building::displayBuilding()
{
    std::cout << "Building ID: " << buildingId << std::endl;
    std::cout << "Address: " << address << std::endl;
    std::cout << "Apartments:" << std::endl;
    for (const auto &apartment : apartments)
    {
        if (apartment != nullptr)
        {
            apartment->displayApartment();
            std::cout << "------------------------" << std::endl;
        }
    }
}
