//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Building.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_BUILDING_H)
#define _BUILDING_H

#include <string>
#include <vector>
#include "Apartment.h"

using namespace std;

class Building
{
public:
	Building(int id, string address);
	void addApartment(Apartment *apartment);
	void removeApartment(int apartmentId);
	void displayBuilding();

private:
	int buildingId;
	string address;
	vector<Apartment *> apartments;
};

#endif //_BUILDING_H
