//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Room.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_ROOM_H)
#define _ROOM_H

#include <string>

using namespace std;

class Room
{
public:
	Room(int id, string name, double size);
	string getName();
	double getSize();
	void displayRoom();

private:
	int roomId;
	string name;
	double size;
};

#endif //_ROOM_H
