//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Room.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Room.h"
#include <iostream>

Room::Room(int id, string name, double size)
{
    this->roomId = id;
    this->name = name;
    this->size = size;
}

string Room::getName()
{
    return name;
}

double Room::getSize()
{
    return size;
}

void Room::displayRoom()
{
    cout << "Room ID: " << roomId << endl;
    cout << "Name: " << name << endl;
    cout << "Size: " << size << " m2" << endl;
}
