//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.h
//  @ Date : 07/04/2025
//  @ Author :
//
//

#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <vector>
#include <map>
#include <string>
#include "User.h"

using namespace std;

class System
{
public:
	bool authenticate(const string &identifier, const string &password);
	bool registerUser(const string &identifier, const string &password);
	void addUser(User *user);
	void removeUser(const string &identifier);
	System();
	~System();

private:
	vector<User *> users;
	map<string, string> userDatabase;
	bool isUserRegistered;
};

#endif //_SYSTEM_H
