//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 07/04/2025
//  @ Author :
//
//

#if !defined(_USER_H)
#define _USER_H

#include <string>

using namespace std;

class User
{
public:
	void provideCredentials();
	void openHomePage();
	void requestRegistration();
	void sendData();
	void login();
	void logout();
	User(string id, string pass);
	~User();

private:
	string identifier;
	string password;
	bool isLoggedIn;
};

#endif //_USER_H
