//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 07/04/2025
//  @ Author :
//
//

#include "User.h"
#include <iostream>

void User::provideCredentials()
{
    cout << "Providing credentials for user: " << identifier << endl;
}

void User::openHomePage()
{
    if (isLoggedIn)
    {
        cout << "Opening homepage for user: " << identifier << endl;
    }
    else
    {
        cout << "Please log in first" << endl;
    }
}

void User::requestRegistration()
{
    cout << "Requesting registration for user: " << identifier << endl;
}

void User::sendData()
{
    if (isLoggedIn)
    {
        cout << "Sending data for user: " << identifier << endl;
    }
    else
    {
        cout << "Please log in first" << endl;
    }
}

void User::login()
{
    isLoggedIn = true;
    cout << "User " << identifier << " logged in" << endl;
}

void User::logout()
{
    isLoggedIn = false;
    cout << "User " << identifier << " logged out" << endl;
}

User::User(string id, string pass) : identifier(id), password(pass), isLoggedIn(false) {}

User::~User()
{
    if (isLoggedIn)
    {
        logout();
    }
}
