//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.cpp
//  @ Date : 25/03/2025
//  @ Author : 
//
//


#include "Car.h"
#include <string>
#include <iostream>
#include <sstream>

using namespace std;

Car::Car(const string& producer, int year, const string& model, double price) 
    : Vehicle(producer, year, "Gasoline", 1500), 
      modelName(model), 
      askingPrice(price), 
      seatingCapacity(5) {}

string Car::getDetails() {
    stringstream ss;
    ss << "Model: " << modelName << "\n"
       << "Price: $" << askingPrice << "\n"
       << "Seating Capacity: " << seatingCapacity << "\n"
       << getBasicInfo();
    return ss.str();
}

void Car::honkHorn() {
    cout << "Beep! Beep!" << endl;
}

