//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.h
//  @ Date : 25/03/2025
//  @ Author :
//
//

#if !defined(_CAR_H)
#define _CAR_H

#include "Vehicle.h"
#include <string>

using namespace std;

class Car : public Vehicle
{
public:
	Car(const string &producer, int year, const string &model, double price);
	string getDetails();
	void honkHorn();

private:
	string modelName;
	double askingPrice;
	int seatingCapacity;
};

#endif //_CAR_H
