//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CarDealership.h
//  @ Date : 25/03/2025
//  @ Author :
//
//

#if !defined(_CARDEALERSHIP_H)
#define _CARDEALERSHIP_H

#include "Car.h"
#include <string>
#include <list>
#include <set>

using namespace std;

class CarDealership
{
public:
	CarDealership(const string &name, const string &location)
		: dealershipName(name), location(location), totalCarsInStock(0) {};
	~CarDealership() {};
	void addCarToInventory(Car *car);
	void removeCarFromInventory(Car *car);
	list<Car *> getCarsByModel(const string &model);
	void sellCar(Car *car, const string &customerName, double salePrice);

private:
	string dealershipName;
	string location;
	set<string> availableCarModels;
	int totalCarsInStock;
	list<Car *> inventory;
};

#endif //_CARDEALERSHIP_H
