//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CarDealership.cpp
//  @ Date : 25/03/2025
//  @ Author :
//
//

#include "CarDealership.h"
#include "Car.h"
#include <string>
#include <list>
#include <iostream>
#include <sstream>

using namespace std;

void CarDealership::addCarToInventory(Car *car)
{
    inventory.push_back(car);
    availableCarModels.insert(car->getDetails());
    totalCarsInStock++;
    cout << "Added new car to inventory. Total cars: " << totalCarsInStock << endl;
}

void CarDealership::removeCarFromInventory(Car *car)
{
    inventory.remove(car);
    totalCarsInStock--;
    cout << "Removed car from inventory. Total cars: " << totalCarsInStock << endl;
}

list<Car *> CarDealership::getCarsByModel(const string &model)
{
    list<Car *> matchingCars;
    for (Car *car : inventory)
    {
        if (car->getDetails().find(model) != string::npos)
        {
            matchingCars.push_back(car);
        }
    }
    return matchingCars;
}

void CarDealership::sellCar(Car *car, const string &customerName, double salePrice)
{
    cout << "\nSelling car to " << customerName << endl;
    cout << "Sale price: $" << salePrice << endl;
    cout << "\nCar details:\n"
         << car->getDetails() << endl;

    removeCarFromInventory(car);
    cout << "\nSale completed!" << endl;
}
