//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehicle.h
//  @ Date : 25/03/2025
//  @ Author : 
//
//


#if !defined(_VEHICLE_H)
#define _VEHICLE_H

#include <string>

using namespace std;

class Vehicle {
public:
	Vehicle(const string &producer, int productionYear, const string &powerSource, int weightInKilograms)
		: producer(producer), productionYear(productionYear), powerSource(powerSource), weightInKilograms(weightInKilograms) {}
	void startEngine();
	void stopEngine();
	string getBasicInfo();
private:
	string producer;
	int productionYear;
	string powerSource;
	int weightInKilograms;
};

#endif  //_VEHICLE_H
