//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehicle.cpp
//  @ Date : 25/03/2025
//  @ Author :
//
//

#include "Vehicle.h"
#include <string>
#include <iostream>
#include <sstream>

using namespace std;

void Vehicle::startEngine()
{
    cout << "Engine started\n";
}

void Vehicle::stopEngine()
{
    cout << "Engine stopped\n";
}

string Vehicle::getBasicInfo()
{
    stringstream ss;
    ss << "Producer: " << producer << "\n"
       << "Year: " << productionYear << "\n"
       << "Power source: " << powerSource << "\n"
       << "Weight: " << weightInKilograms << " kg";
    return ss.str();
}
