//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailSender.cpp
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#include "EmailSender.h"
#include "Message.h"
#include <iostream>
#include <string>

void EmailSender::sendEmail(const Message& message) {
    cout << "Wysylanie e-maila z adresu: " << senderAddress << endl;
    cout << "Do: " << message.getRecipient() << endl;
    cout << "Temat: " << message.getSubject() << endl;
    cout << "Tresc: " << message.getContent() << endl;
    cout << "E-mail zostal wyslany." << endl;
}

EmailSender::EmailSender(const string& senderAddress) : senderAddress(senderAddress) {}

EmailSender::~EmailSender() {}

