//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : EmailSender.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_EMAILSENDER_H)
#define _EMAILSENDER_H

#include "Message.h"
#include <string>

using namespace std;

class EmailSender {
public:
	void sendEmail(const Message& message);
	EmailSender(const string& senderAddress);
	~EmailSender();
private:
	string senderAddress;
};

#endif  //_EMAILSENDER_H
