//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Message.cpp
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#include "Message.h"

string Message::getRecipient() const {
    return recipient;
}

string Message::getSubject() const {
    return subject;
}

string Message::getContent() const {
    return content;
}

Message::Message(const string& recipient, const string& subject, const string& content) : recipient(recipient), subject(subject), content(content) {}

Message::~Message() {}

