//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Message.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_MESSAGE_H)
#define _MESSAGE_H

#include <string>

using namespace std;

class Message {
public:
	string getRecipient() const;
	string getSubject() const;
	string getContent() const;
	Message(const string& recipient, const string& subject, const string& content);
	~Message();
private:
	string recipient;
	string subject;
	string content;
};

#endif  //_MESSAGE_H
