//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_ORDER_H)
#define _ORDER_H

#include <vector>
#include "OrderItem.h"

class Order
{
public:
	Order(int orderId, int customerId);
	void addItem(OrderItem *item);
	void removeItem(int itemId);
	double getTotalAmount();
	int getOrderId();
	int getCustomerId();

private:
	int orderId;
	int customerId;
	std::vector<OrderItem *> items;
};

#endif //_ORDER_H
