//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderItem.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_ORDERITEM_H)
#define _ORDERITEM_H

#include "Product.h"

class OrderItem
{
public:
	OrderItem(int itemId, int quantity, Product *product);
	int getItemId();
	int getQuantity();
	Product *getProduct();
	double calculateSubtotal();

private:
	int itemId;
	int quantity;
	Product *product;
};

#endif //_ORDERITEM_H
