//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderItem.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "OrderItem.h"

OrderItem::OrderItem(int itemId, int quantity, Product *product)
{
    this->itemId = itemId;
    this->quantity = quantity;
    this->product = product;
}

int OrderItem::getItemId()
{
    return itemId;
}

int OrderItem::getQuantity()
{
    return quantity;
}

Product *OrderItem::getProduct()
{
    return product;
}

double OrderItem::calculateSubtotal()
{
    return quantity * product->getPrice();
}
