//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Order.h"

Order::Order(int orderId, int customerId)
{
    this->orderId = orderId;
    this->customerId = customerId;
}

void Order::addItem(OrderItem *item)
{
    items.push_back(item);
}

void Order::removeItem(int itemId)
{
    for (auto it = items.begin(); it != items.end(); ++it)
    {
        if ((*it)->getItemId() == itemId)
        {
            items.erase(it);
            break;
        }
    }
}

double Order::getTotalAmount()
{
    double total = 0.0;
    for (const auto &item : items)
    {
        total += item->calculateSubtotal();
    }
    return total;
}

int Order::getOrderId()
{
    return orderId;
}

int Order::getCustomerId()
{
    return customerId;
}
