//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_PRODUCT_H)
#define _PRODUCT_H

#include <string>

class Product
{
public:
	Product(int productId, const std::string &name, double price);
	int getProductId() const;
	std::string getName();
	double getPrice();

private:
	int productId;
	std::string name;
	double price;
};

#endif //_PRODUCT_H
