//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Product.h"

Product::Product(int productId, const std::string &name, double price)
{
    this->productId = productId;
    this->name = name;
    this->price = price;
}

int Product::getProductId() const
{
    return productId;
}

std::string Product::getName()
{
    return name;
}

double Product::getPrice()
{
    return price;
}
