//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Attachment.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_ATTACHMENT_H)
#define _ATTACHMENT_H

#include <string>

using namespace std;

class Attachment {
public:
	Attachment(const string& filename, int size);
	string getFilename();
	int getSize();
private:
	string filename;
	int size;
};

#endif  //_ATTACHMENT_H
