//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Attachment.cpp
//  @ Date : 18/03/2025
//  @ Author : 
//
//

#include "Attachment.h"

Attachment::Attachment(const string& filename, int size) : filename(filename), size(size) {}

string Attachment::getFilename() {
    return filename;
}

int Attachment::getSize() {
    return size;
}

