//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Email.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_EMAIL_H)
#define _EMAIL_H

#include "Attachment.h"
#include <list>

class Email {
public:
	void addAttachment(Attachment& attachment);
	Attachment& getAttachment(int index);
	int getAttachmentCount();
private:
	string subject;
	string body;
	list<Attachment> attachments;
};

#endif  //_EMAIL_H
