//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Email.cpp
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#include "Email.h"
#include "Attachment.h"
#include <list>

void Email::addAttachment(Attachment& attachment) {
    attachments.push_back(attachment);
}

Attachment& Email::getAttachment(int index) {
    auto it = attachments.begin();
    advance(it, index);
    return *it;
}

int Email::getAttachmentCount() {
    return attachments.size();
}

