//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Potega.h"

Potega::Potega(int podstawa, int wykladnik)
{
    this->podstawa = podstawa;
    this->wykladnik = wykladnik;
}

double Potega::oblicz()
{
    double result = 1.0;
    int absWykladnik = wykladnik;

    if (wykladnik < 0)
    {
        absWykladnik = -wykladnik;
    }

    for (int i = 0; i < absWykladnik; i++)
    {
        result *= podstawa;
    }

    if (wykladnik < 0)
    {
        if (result != 0)
        {
            result = 1.0 / result;
        }
    }

    return result;
}
