//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_POTEGA_H)
#define _POTEGA_H

class Potega
{
public:
	Potega(int podstawa, int wykladnik);
	double oblicz();

private:
	int podstawa;
	int wykladnik;
};

#endif //_POTEGA_H
