//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Prawdopodobienstwo.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_PRAWDOPODOBIENSTWO_H)
#define _PRAWDOPODOBIENSTWO_H

#include "Potega.h"
#include "SymbolNewtona.h"

class Prawdopodobienstwo
{
public:
	Prawdopodobienstwo(int liczbaProb, int liczbaSukcesow, double prawdopodobienstwoSukcesu);
	bool sprawdzPoprawnoscDanych();
	double obliczPrawdopodobienstwo();
	void wprowadzDane(int liczbaProb, int liczbaSukcesow, double prawdopodobienstwoSukcesu);

private:
	int liczbaProb;
	int liczbaSukcesow;
	double prawdopodobienstwoSukcesu;
	bool danePoprawne;
	double wynik;
	Potega *potega;
	SymbolNewtona *symbolNewtona;
};

#endif //_PRAWDOPODOBIENSTWO_H
