//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_SILNIA_H)
#define _SILNIA_H

class Silnia
{
public:
	Silnia(int n);
	long long oblicz();

private:
	int n;
};

#endif //_SILNIA_H
