//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "Silnia.h"

Silnia::Silnia(int n)
{
    this->n = n;
}

long long Silnia::oblicz()
{
    if (n < 0)
    {
        return 0;
    }

    long long result = 1;
    for (int i = 2; i <= n; i++)
    {
        result *= i;
    }
    return result;
}
