//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.h
//  @ Date : 13/04/2025
//  @ Author :
//
//

#if !defined(_SYMBOLNEWTONA_H)
#define _SYMBOLNEWTONA_H

#include "Silnia.h"

class SymbolNewtona
{
public:
	SymbolNewtona(int n, int k);
	double oblicz();

private:
	int n;
	int k;
	Silnia *silnia;
};

#endif //_SYMBOLNEWTONA_H
