//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.cpp
//  @ Date : 13/04/2025
//  @ Author :
//
//

#include "SymbolNewtona.h"

SymbolNewtona::SymbolNewtona(int n, int k)
{
    this->n = n;
    this->k = k;
    this->silnia = nullptr;
}

double SymbolNewtona::oblicz()
{

    if (k > n || n < 0 || k < 0)
    {
        return 0;
    }

    Silnia silniaN(n);
    Silnia silniaK(k);
    Silnia silniaNK(n - k);

    long long licznik = silniaN.oblicz();
    long long mianownik = silniaK.oblicz() * silniaNK.oblicz();

    if (mianownik == 0)
    {
        return 0;
    }

    return static_cast<double>(licznik) / mianownik;
}
