//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.cpp
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#include "Car.h"
#include "Person.h"

void Car::setOwner(Person* newOwner) {
    owner = newOwner;
}

Person* Car::getOwner() {
    return owner;
}

