//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_CAR_H)
#define _CAR_H

class Person;

class Car {
public:
	void setOwner(Person* newOwner);
	Person* getOwner();
private:
	Person* owner;
};

#endif  //_CAR_H
