//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.h
//  @ Date : 18/03/2025
//  @ Author : 
//
//


#if !defined(_PERSON_H)
#define _PERSON_H

#include "Car.h"

class Person {
public:
	void setCar(Car* newCar);
	Car* getCar();
private:
	Car* car;
};

#endif  //_PERSON_H
